# Simple workflow for deploying static content to GitHub Pages
name: Deploy benchmark reports to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run All Events
        run: mkdir -p target/criterion && cargo run --release --features basic_profiler -- all > target/criterion/results.txt
        env:
          RUSTFLAGS: -Ctarget-cpu=native
      - name: Bench
        run: cargo bench --bench criterion -- --quick
        env:
          RUSTFLAGS: -Ctarget-cpu=native
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload criterion reports
          path: 'target/criterion'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
